name: ci

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Pull Source
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: "3.10"

    - name: Establish Versioning, Tags, and Labels
      id: vtl
      uses: mapped/action-vtl@latest
      with:
        baseVersion: 1.0.0
        gitHubToken: ${{ secrets.GITHUB_TOKEN }}

    - name: publish botbuilder-integration-aiohttp-forked
      run: |
        echo version: $packageVersion
        python setup.py sdist
        curl -F package=@./dist/botbuilder-integration-aiohttp-forked-$packageVersion.tar.gz https://${{ secrets.FURY_PUSH_TOKEN }}@push.fury.io/mapped/
      env:
        packageVersion: ${{ steps.vtl.outputs.ver_semVerNoMeta}}
      working-directory: ./libraries/botbuilder-integration-aiohttp
    
    - name: publish botframework-connector-forked
      run: |
        echo version: $packageVersion
        python setup.py sdist
        curl -F package=@./dist/botframework-connector-forked-$packageVersion.tar.gz https://${{ secrets.FURY_PUSH_TOKEN }}@push.fury.io/mapped/
      env:
        packageVersion: ${{ steps.vtl.outputs.ver_semVerNoMeta}}
      working-directory: ./libraries/botframework-connector
    
    - name: publish botframework-streaming-forked
      run: |
        echo version: $packageVersion
        python setup.py sdist
        curl -F package=@./dist/botframework-streaming-forked-$packageVersion.tar.gz https://${{ secrets.FURY_PUSH_TOKEN }}@push.fury.io/mapped/
      env:
        packageVersion: ${{ steps.vtl.outputs.ver_semVerNoMeta}}
      working-directory: ./libraries/botframework-streaming
    
    - name: publish botbuilder-core-forked
      run: |
        echo version: $packageVersion
        python setup.py sdist
        curl -F package=@./dist/botbuilder-core-forked-$packageVersion.tar.gz https://${{ secrets.FURY_PUSH_TOKEN }}@push.fury.io/mapped/
      env:
        packageVersion: ${{ steps.vtl.outputs.ver_semVerNoMeta}}
      working-directory: ./libraries/botbuilder-core
